DEV:
  REGION: 'us-west-2'
  CFM:
    VPC:
      STACK_NAME: 'VPCtestStack'
      TEMPLATE_PATH: '/lib/etude_for_aws/cfm/vpc/cfm_templates/'
      TEMPLATE_FILE_TYPE_01: 'vpc-1az-1subnet-pub.template'
      TEMPLATE_FILE_TYPE_02: 'vpc-1az-2subnet-pub.template'
      TEMPLATE_FILE_TYPE_03: 'vpc-1az-2subnet-pub-pri.template'
      TEMPLATE_FILE_TYPE_04: 'vpc-2az-2subnet-pri.template'
      TEMPLATE_FILE_TYPE_05: 'vpc-2az-2subnet-pub.template'
      TEMPLATE_FILE_TYPE_06: 'vpc-2az-2subnet-pub-pri.template'
      TEMPLATE_FILE_TYPE_07: 'vpc-2az-4subnet-pub-pri.template'
      TEMPLATE_PARAMS_AZ1: 'us-west-2a'
      TEMPLATE_PARAMS_AZ2: 'us-west-2b'
      TEMPLATE_PARAMS_AZ3: 'us-west-2c'
      TAG_VALUE: 'test'
  VPC:
    VPC_TAGS:
      NAME:
        KEY: 'Name'
        VALUE: 'TestVpc'
      GROUP:
        KEY: 'GroupName'
        VALUE: 'TestVpcGroup'
    VPC_CIDR_BLOCK: '10.0.0.0/16'
    SUBNETS:
      PUBLIC:
        - CONFIG:
            SUBNET_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'TestVpcPublicSubnet1'
            SUBNET_CIDR_BLOCK:
              - '10.0.0.0/24'
            AZ:
              - 'us-west-2a'
      PRIVATE:
        - CONFIG:
            SUBNET_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'TestVpcPrivateSubnet1'
            SUBNET_CIDR_BLOCK:
              - '10.0.1.0/24'
            AZ:
              - 'us-west-2a'
    ROUTE_TABLES:
      PUBLIC:
        - CONFIG:
            ROUTE_TABLE_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'TestVpcPublicRouteTable1'
            DESTINATION_CIDR_BLOCK:
              - '0.0.0.0/0'
      PRIVATE:
        - CONFIG:
            ROUTE_TABLE_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'TestVpcPrivateSubnet1'
            DESTINATION_CIDR_BLOCK:
              - '10.0.0.0/16'
    INTERNET_GATEWAY:
      IG_TAGS:
        NAME:
          KEY: 'Name'
          VALUE: 'TestVpcInternetGateway'
    VPN:
      CUSTOMER_GATEWAYS:
        - CONFIG:
            CUSTOMER_GATEWAY:
              BGP_ASN: '65534'
              PUBLIC_IP: '110.4.157.54'
              TYPE: 'ipsec.1'
              TAGS:
                NAME:
                  KEY: 'Name'
                  VALUE: 'TestCustomerGateway'
      VPN_GATEWAY:
        TYPE: 'ipsec.1'
        DESTINATION_CIDR_BLOCKS:
          - CIDR: '192.168.0.0/16'
        TAGS:
          NAME:
            KEY: 'Name'
            VALUE: 'TestVpnGateway'
      VPN_CONNECTIONS:
        - CONFIG:
            VPN_CONNECTION:
              TYPE: 'ipsec.1'
              OPTIONS:
                STATIC_ROUTES_ONLY: true
              TAGS:
                NAME:
                  KEY: 'Name'
                  VALUE: 'TestVpnConnection'

  EC2:
    INSTANCE_TAGS:
      NAME_VALUE: 'MyGroovyInstance'
      GROUP_VALUE: 'MyGroovyGroup'
    SECURITY_GROUP_NAME: 'MyGroovySecurityGroup'
    SECURITY_GROUP_DESCRIPTION: 'Security group for MyGroovyInstance'
    KEY_PAIR_NAME: 'my-key-pair'
    KEY_PAIR_PATH: '/lib/etude_for_aws/ec2/'
    IMAGE_ID: 'ami-4836a428'
    INSTANCE_TYPE: 't2.micro'
    MIN_COUNT: '1'
    MAX_COUNT: '1'
    INSTANCES:
      PUBLIC:
        - CONFIG:
            INSTANCE_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'PublicInstance1'
      PRIVATE:
        - CONFIG:
            INSTANCE_TAGS:
              - NAME:
                  KEY: 'Name'
                  VALUE: 'PrivateInstance1'