DEV:
  REGION: 'us-west-2'
  VPC:
    STACK_NAME: 'VPCtestStack'
    TEMPLATE_PATH: '/lib/etude_for_aws/vpc/cfm_templates/'
    TEMPLATE_FILE_TYPE_01: 'vpc-1az-1subnet-pub.template'
    TEMPLATE_FILE_TYPE_02: 'vpc-1az-2subnet-pub.template'
    TEMPLATE_FILE_TYPE_03: 'vpc-1az-2subnet-pub-pri.template'
    TEMPLATE_FILE_TYPE_04: 'vpc-2az-2subnet-pri.template'
    TEMPLATE_FILE_TYPE_05: 'vpc-2az-2subnet-pub.template'
    TEMPLATE_FILE_TYPE_06: 'vpc-2az-2subnet-pub-pri.template'
    TEMPLATE_FILE_TYPE_07: 'vpc-2az-4subnet-pub-pri.template'
    TEMPLATE_PARAMS_AZ1: 'us-west-2a'
    TEMPLATE_PARAMS_AZ2: 'us-west-2b'
    TEMPLATE_PARAMS_AZ3: 'us-west-2c'
    TAG_VALUE: 'test'
  EC2:
    SECURITY_GROUP_NAME: 'MyGroovySecurityGroup'
    SECURITY_GROUP_DESCRIPTION: 'Security group for MyGroovyInstance'
    KEY_PAIR_NAME: 'my-key-pair'
    KEY_PAIR_PATH: '/lib/etude_for_aws/ec2/'
    IMAGE_ID: 'ami-4836a428'
    INSTANCE_TYPE: 't2.micro'
    MIN_COUNT: '1'
    MAX_COUNT: '1'
    INSTANCE_TAGS:
      NAME_VALUE: 'MyGroovyInstance'
      GROUP_VALUE: 'MyGroovyGroup'

