@startuml

package Aws {
  class EC2::Client
  class EC2::Resource
}

package CFM {
  class CFM::Vpc
}

Interface CertificationHelper
Interface ConfigurationHelper

package EC2 {
  Interface VpcInterface
  VpcInterface <|-u- CFM::Vpc

  class Ec2 {
    create()
    destroy()
    start()
    stop()
    reboot()
  }
  CertificationHelper <|-- Configuration
  ConfigurationHelper <|-- Configuration
  Configuration -u-> EC2::Client
  Configuration -u-> EC2::Resource
  Ec2 -r-> VpcInterface
  Ec2 "1" *-l- "1" Configuration
  Ec2 "1" *-- "1..*" Ec2Instance
  Ec2 "1" *-- "1" KeyPair
  Ec2 "1" *-- "1" SecurityGroup

}

@enduml