require 'etude_for_aws/version'
require 'etude_for_aws/helpers/certification_helper'
require 'etude_for_aws/helpers/configuration_helper'
require 'etude_for_aws/ec2/vpc_interface'
require 'etude_for_aws/cfm/configuration'
require 'etude_for_aws/cfm/vpc/vpc'
require 'etude_for_aws/cfm/vpc/null_vpc'
require 'etude_for_aws/cfm/vpc/one_az_one_public_subnet_vpc'
require 'etude_for_aws/cfm/vpc/one_az_two_public_subnet_vpc'
require 'etude_for_aws/cfm/vpc/one_az_two_public_and_private_subnet_vpc'
require 'etude_for_aws/cfm/vpc/two_az_two_private_subnet_vpc'
require 'etude_for_aws/cfm/vpc/two_az_two_public_subnet_vpc'
require 'etude_for_aws/cfm/vpc/two_az_one_public_subnet_and_private_subnet_vpc'
require 'etude_for_aws/cfm/vpc/two_az_two_public_subnet_and_private_subnet_vpc'
require 'etude_for_aws/vpc/simple_vpc'
require 'etude_for_aws/vpc/configuration'
require 'etude_for_aws/vpc/vpc'
require 'etude_for_aws/vpc/subnet'
require 'etude_for_aws/vpc/internet_gateway'
require 'etude_for_aws/vpc/route_table'
require 'etude_for_aws/ec2/ec2'
require 'etude_for_aws/ec2/configuration'
require 'etude_for_aws/ec2/security_group'
require 'etude_for_aws/ec2/key_pair'
require 'etude_for_aws/ec2/ec2_instance'

module EtudeForAws
  # Your code goes here...
end
