@startuml
cloud Internet
frame "AWS" {
frame "VPC" {
    [RouteTable] -- PrivateSubnet1
    [RouteTable] -- PrivateSubnet2
    frame "AZ1" {
      frame "PrivateSubnet1" {
      }
    }
    frame "AZ2" {
      frame "PrivateSubnet2" {
      }
    }
}
}
note right of PrivateSubnet1
  10.0.2.0/24
end note
note right of PrivateSubnet2
  10.0.3.0/24
end note
@enduml