@startuml

package Aws {
  class CloudFormation
}

package EC2 {
  Interface VpcInterface
}

Interface CertificationHelper
Interface ConfigurationHelper

package CFM {
  class Vpc {
    create()
    destroy()
  }

  Vpc <|-- VpcInterface
  CertificationHelper <|-- Configuration
  ConfigurationHelper <|-- Configuration
  Configuration -l-> CloudFormation
  Vpc *-l- Configuration
  Vpc <|-- NullVpc
  Vpc <|-- OneAzOnePublicSubnetVpc
  Vpc <|-- OneAzTwoPublicAndPrivateSubnetVpc
  Vpc <|-- OneAzTwoPublicSubnetVpc
  Vpc <|-- TwoAzOnePublicSubnetAndPrivateSubnetVpc
  Vpc <|-- TwoAzTwoPrivateSubnetVpc
  Vpc <|-- TwoAzTwoPublicSubnetAndPrivateSubnetVpc
  Vpc <|-- TwoAzTwoPublicSubnetVpc
}

@enduml